version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://saas_user:saas_pass@db:5432/saas_shop
      - SECRET_KEY=dev-secret-key
    volumes:
      - .:/app
      - uploads:/app/app/static/uploads
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=saas_shop
      - POSTGRES_USER=saas_user
      - POSTGRES_PASSWORD=saas_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  uploads:
