services:
  - type: web
    name: saas-shop
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x initialize.sh
      ./initialize.sh
    startCommand: |
      chmod +x startup.sh
      ./startup.sh
    plan: starter
    autoDeploy: true
    envVars:
      - key: WEB_CONCURRENCY
        value: "2"
      - key: MAX_WORKERS
        value: "2"
      - key: PYTHON_UNBUFFERED
        value: "true"
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: saas-shop-db
          property: connectionString
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false
      - key: DB_SCHEMA
        value: AndriIT
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        generateValue: true

databases:
  - name: saas-shop-db
    databaseName: saas_shop
    user: saas_shop_user
    postgresMajorVersion: "14"  # Указываем конкретную версию PostgreSQL
    ipAllowList: []  # Доступ из всех расположений
